name: Dialyzer

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-dialyzer-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-dialyzer-
      - uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-build-dialyzer-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-dialyzer-
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 22.4
          elixir-version: 1.12
      - run: mix deps.get
      - run: MIX_ENV=dev mix check --only dialyzer
